#!/bin/bash

set -e

ROOTDIR=/mnt

# Create /var/log/journal...
mkdir -p ${ROOTDIR}/var/log/journal
chmod 2755 ${ROOTDIR}/var/log/journal
chroot ${ROOTDIR} chown root:systemd-journal /var/log/journal

# Make sure /usr is newer than /etc
touch ${ROOTDIR}/usr

# Switch subvolume back to read-only
btrfs property set ${ROOTDIR}/os/.snapshots/1/snapshot ro true

umount -R ${ROOTDIR}/usr

touch ${ROOTDIR}/usr

# Umount everything
umount -R ${ROOTDIR}
