#!/bin/bash

set -e

ROOTDIR=/mnt

# We need the root account and systemd users in initramfs
chroot ${ROOTDIR} systemd-sysusers system-user-root.conf
chroot ${ROOTDIR} systemd-sysusers system-group-hardware.conf
for i in {ROOTDIR}/usr/lib/sysusers.d/systemd*.conf; do
    chroot ${ROOTDIR} systemd-sysusers $(basename $i)
done

mkdir -p ${ROOTDIR}/etc/sysconfig

# copy snapper configs
cp -av ${ROOTDIR}/usr/share/factory/etc/snapper ${ROOTDIR}/etc/
cp -a ${ROOTDIR}/usr/share/fillup-templates/sysconfig.snapper ${ROOTDIR}/etc/sysconfig/snapper
# Initialize missing snapper stuff
chroot ${ROOTDIR} /usr/lib/snapper/installation-helper --step 4
sed -e 's|/mnt/usr|/usr|g' /etc/snapper/configs/usr > ${ROOTDIR}/etc/snapper/configs/usr
sed -i -e 's|SNAPPER_CONFIGS=.*|SNAPPER_CONFIGS="root usr"|g' ${ROOTDIR}/etc/sysconfig/snapper

# configure locale and timezone
echo "LANG=en_US.UTF-8" > ${ROOTDIR}/etc/locale.conf
ln -sf /usr/share/zoneinfo/UTC ${ROOTDIR}/etc/localtime
# Systemd controls the console font now
echo FONT="eurlatgr.psfu" >> /etc/vconsole.conf

mkdir -p ${ROOTDIR}/etc/systemd/network
# Enable DHCP on enp*
cat << EOT > ${ROOTDIR}/etc/systemd/network/enp-dhcp.network
[Match]
Name=enp*

[Network]
DHCP=yes
EOT
