#!/bin/bash

set -e

ROOTDIR=/mnt

# Create compat symlinks because of usrMove
ln -sf usr/bin ${ROOTDIR}/bin
ln -sf usr/sbin ${ROOTDIR}/sbin
ln -sf usr/lib ${ROOTDIR}/lib
ln -sf usr/lib64 ${ROOTDIR}/lib64
mkdir ${ROOTDIR}/dev
mkdir ${ROOTDIR}/sys
mkdir ${ROOTDIR}/proc
# dracut does not work without this directories
mkdir ${ROOTDIR}/run
mkdir -p ${ROOTDIR}/var/tmp
# configure locale and timezone
echo "LANG=en_US.UTF-8" > ${ROOTDIR}/etc/locale.conf
ln -sf /usr/share/zoneinfo/UTC ${ROOTDIR}/etc/localtime

# lo network config
mkdir -p ${ROOTDIR}/etc/sysconfig/network
echo << EOT >> ${ROOTDIR}/etc/sysconfig/network/ifcfg-lo
# Loopback (lo) configuration
IPADDR=127.0.0.1/8
NETMASK=255.0.0.0
NETWORK=127.0.0.0
STARTMODE=nfsroot
BOOTPROTO=static
USERCONTROL=no
FIREWALL=no
EOT
chmod 600 ${ROOTDIR}/etc/sysconfig/network/ifcfg-lo

