#!/bin/bash

source $(dirname $0)/logging

ROOTDIR=/mnt

USRDEV=$(awk '!/^#/ && ($2 == "/usr") { print $1 }' ${ROOTDIR}/etc/fstab)
log_info "USRDEV = $USRDEV"
run "snapper -c usr create-config ${ROOTDIR}/usr"
run "snapper -c usr setup-quota"
run "snapper -c usr create"

# Add fstab entries
run "echo \"${USRDEV}  /usr/.snapshots          btrfs  subvol=/.snapshots,x-initrd.mount     0  0\" >> ${ROOTDIR}/etc/fstab"
