#!/bin/bash

source $(dirname $0)/logging

ROOTDIR=/mnt

# Create compat symlinks because of usrMove
run "ln -sf usr/bin ${ROOTDIR}/bin"
run "ln -sf usr/sbin ${ROOTDIR}/sbin"
run "ln -sf usr/lib ${ROOTDIR}/lib"
run "ln -sf usr/lib64 ${ROOTDIR}/lib64"
# mpkir -p: Do not return an error if it already exists
run "mkdir -p ${ROOTDIR}/dev"
run "mkdir -p ${ROOTDIR}/sys"
run "mkdir -p ${ROOTDIR}/proc"
# dracut/install-kernel do not work without this directories
run "mkdir -p ${ROOTDIR}/run"
run "mkdir -p ${ROOTDIR}/var/tmp"
run "mkdir -p ${ROOTDIR}/tmp"
run "chmod 1777 ${ROOTDIR}/tmp"
