#!/bin/bash

source $(dirname $0)/logging

ROOTDIR=/mnt

USRDEV=$(awk '!/^#/ && ($2 == "/os") { print $1 }' ${ROOTDIR}/etc/fstab)
log_info "USRDEV = $USRDEV"
run "snapper -c usr create-config ${ROOTDIR}/os"
run "snapper -c usr create"

# Add fstab entries
run "echo \"${USRDEV}  /os/.snapshots          btrfs  subvol=/.snapshots             0  0\" >> ${ROOTDIR}/etc/fstab"
run "echo \"/sysroot/os/.snapshots/1/snapshot/usr      /usr                    none   bind,ro,x-initrd.mount         0  0\" >> ${ROOTDIR}/etc/fstab"
