#!/bin/bash

set -e

ROOTDIR=/mnt

#USRDEV=$(awk '!/^#/ && ($2 == "/usr") { print $1 }' ${ROOTDIR}/etc/fstab)
snapper -c usr create-config ${ROOTDIR}/os
snapper -c usr create
btrfs property set ${ROOTDIR}/os/.snapshots/1/snapshot ro false
mount -o bind ${ROOTDIR}/os/.snapshots/1/snapshot ${ROOTDIR}/usr
echo "/sysroot/os/.snapshots/1/snapshot /usr none bind,ro,x-initrd.mount 0 0" >> ${ROOTDIR}/etc/fstab
