#!/bin/sh

. $(dirname $0)/logging

FILES=".vmlinuz.hmac System.map sysctl.conf vmlinuz"

for i in ${FILES} initrd ; do
    run "rm -f /boot/\"${i}\"*"
done

# Install the kernel
for i in /usr/lib/modules/* ; do
    KVER=$(basename "$i")
    for f in .vmlinuz.hmac System.map sysctl.conf vmlinuz; do
        run "cp -a \"/usr/lib/modules/$KVER/$f\" \"/boot/$f-$KVER\""
    done
    log_info "- - - dracut for $KVER - - -"
    run "dracut --kver \"$KVER\""
    log_info "- - - end dracut - - -"
done
